name: ssb-pub
image: debian-9-x64
min_size: 1gb
config:
  #cloud-config
  packages:
    - git
  runcmd:
    - git clone https://github.com/ahdinosaur/ssb-pub
    - source ssb-pub/source
    - ssb-pub-install
